# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l-KwtSub-zEixqYzukLUOKa0h3ZPaSfJ
"""

# 1. Menampilkan output numerik
print("=== Output Numerik ===")
numerik = 42
print("Numerik:", numerik)


# 2. Mendeklarasikan variabel float
float_1 = 10.5
print("\n=== Nilai Float ===")
print("float_1:", float_1)

# 3. Menampilkan output string
print("\n=== Output String ===")
string = "Pakma Nyoknyang"
print("String:", string)

# 4. Menampilkan output boolean
print("\n=== Output Boolean ===")
boolean = True
print("Boolean:", boolean)

# 5. Menggunakan if, elif, else
# Menggunakan if, elif, else
print("\n=== Menggunakan if ===")
angka_if = 15  # Ubah nilai ini untuk melihat hasil yang berbeda
if angka_if > 10:
    print(f"{angka_if} lebih besar dari 10")

print("\n=== Menggunakan elif ===")
angka_elif = 5  # Ubah nilai ini untuk melihat hasil yang berbeda
if angka_elif > 10:
    print(f"{angka_elif} lebih besar dari 10")
elif angka_elif < 10:
    print(f"{angka_elif} lebih kecil dari 10")

print("\n=== Menggunakan else ===")
angka_else = 10  # Ubah nilai ini untuk melihat hasil yang berbeda
if angka_else > 10:
    print(f"{angka_else} lebih besar dari 10")
elif angka_else < 10:
    print(f"{angka_else} lebih kecil dari 10")
else:
    print(f"{angka_else} sama dengan 10")



# 6. Menggunakan while
print("\n=== Menggunakan while ===")
count = 1
while count <= 5:
    print("Count:", count)
    count += 1  # Menambah count

# 7. Menggunakan for
print("\n=== Menggunakan for ===")
for i in range(1, 6):  # Looping dari 1 hingga 5
    print("i:", i)